modLoader="javafml" 
loaderVersion="[28,)" 
# issueTrackerURL="http://my.issue.tracker/" 

[[mods]] 
modId="portalmod" 
version="${file.jarVersion}" 
displayName="Portal Mod" 
# updateJSONURL="http://myurl.me/" 
# displayURL="http://example.com/" 
# logoFile="examplemod.png" 
credits="NOONE" 
authors="Some KLel" 
description='''
TBD
'''

[[dependencies.portalmod]] 
    modId="forge" 
    mandatory=true 
    versionRange="[28,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.portalmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
